// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WelnessWebsite.Data;

#nullable disable

namespace WelnessWebsite.Migrations
{
    [DbContext(typeof(WelnessWebsiteContext))]
    [Migration("20230703230237_DayNutrition")]
    partial class DayNutrition
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WelnessWebsite.Models.DailyNutrition", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WeeklyID")
                        .HasColumnType("int");

                    b.Property<int?>("WeeklyNutritionID")
                        .HasColumnType("int");

                    b.Property<int>("caloric")
                        .HasColumnType("int");

                    b.Property<int>("carbon")
                        .HasColumnType("int");

                    b.Property<int>("fat")
                        .HasColumnType("int");

                    b.Property<int>("protein")
                        .HasColumnType("int");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("WeeklyNutritionID");

                    b.ToTable("DailyNutrition");
                });

            modelBuilder.Entity("WelnessWebsite.Models.DailyWorkout", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("WorkoutType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("UserID")
                        .IsUnique();

                    b.ToTable("DailyWorkout");
                });

            modelBuilder.Entity("WelnessWebsite.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("WelnessWebsite.Models.WeeklyNutrition", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<int>("Carbs")
                        .HasColumnType("int");

                    b.Property<int>("Fat")
                        .HasColumnType("int");

                    b.Property<int>("Fiber")
                        .HasColumnType("int");

                    b.Property<int>("Protein")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("WeeklyNutrition");
                });

            modelBuilder.Entity("WelnessWebsite.Models.Workout", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("DailyWorkoutID")
                        .HasColumnType("int");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Muscle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DailyWorkoutID");

                    b.ToTable("Workout");
                });

            modelBuilder.Entity("WelnessWebsite.Models.DailyNutrition", b =>
                {
                    b.HasOne("WelnessWebsite.Models.WeeklyNutrition", null)
                        .WithMany("DailyNutritions")
                        .HasForeignKey("WeeklyNutritionID");
                });

            modelBuilder.Entity("WelnessWebsite.Models.DailyWorkout", b =>
                {
                    b.HasOne("WelnessWebsite.Models.User", null)
                        .WithOne("Workout")
                        .HasForeignKey("WelnessWebsite.Models.DailyWorkout", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WelnessWebsite.Models.WeeklyNutrition", b =>
                {
                    b.HasOne("WelnessWebsite.Models.User", null)
                        .WithOne("WeeklyNutrition")
                        .HasForeignKey("WelnessWebsite.Models.WeeklyNutrition", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WelnessWebsite.Models.Workout", b =>
                {
                    b.HasOne("WelnessWebsite.Models.DailyWorkout", null)
                        .WithMany("Workout")
                        .HasForeignKey("DailyWorkoutID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WelnessWebsite.Models.DailyWorkout", b =>
                {
                    b.Navigation("Workout");
                });

            modelBuilder.Entity("WelnessWebsite.Models.User", b =>
                {
                    b.Navigation("WeeklyNutrition");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("WelnessWebsite.Models.WeeklyNutrition", b =>
                {
                    b.Navigation("DailyNutritions");
                });
#pragma warning restore 612, 618
        }
    }
}
